### PR TITLE
added start-clusters.sh

### PR DESCRIPTION
**Pull request by obeleh**

### CODE REVIEW

**Comment by pascalw** [comment]
Thanks @obeleh! Can you add to the README when this should be used?

**Comment by obeleh** [comment]
Added now :)

**Comment by pascalw** [comment]
Closing as restarting Kind clusters does not seem to work well currently. See https://github.com/kubernetes-sigs/kind/issues/148 for details.

**Comment by BenTheElder** [comment]
:wave: it should be automatic soon :crossed_fingers: https://github.com/kubernetes-sigs/kind/issues/148#issuecomment-618899661

**Comment by pascalw** [comment]
Awesome @BenTheElder, thanks for letting us know!

**Pull request closed without merging**
